### ISSUE TITLE
5V from EHU or other components

### ISSUE THREAD

**Issue by jokubasver** [leighleighleigh/saab-93NG-bluetooth-aux#1]
Hey, very nice project! I was experimenting with integrating a cheap chinese Bluetooth audio module in my EHU. The PCB of the EHU has all the pins marked, so it was easy to integrate the BT module and solder 5V, GND, L and R pins to it. The 5V line was what interested me, as it is already filtered and it turns on and off along with the EHU, making it a good candidate for powering audio devices. There are also some SDA, SCL pads on there, which might be fun to tinker around with.

![IMG_20210607_193706](https://user-images.githubusercontent.com/4341386/128476431-3756da6e-83ff-4f5b-8169-b65d09f547a4.jpg)
![IMG_20210607_193716](https://user-images.githubusercontent.com/4341386/128476515-e2160e81-f7b1-4673-9abf-9a776b0b92d3.jpg)
![IMG_20210607_193729](https://user-images.githubusercontent.com/4341386/128475600-fccb96eb-5737-41b3-a692-3691a5302de4.jpg)

However, the 5V line on the EHU PCB was a bit weird - with the BT module connected to it, everything worked perfectly - 5V is on when the EHU is on, and 5V is off when the EHU is off. However, it seemed like the EHU wouldn't turn off completely - the BT module and EHU was powered down with the key out of the ignition, yet the current draw from the battery was very high. Next morning I had a flat battery, I undid my mods and the current draw returned to normal.

Have you considered or have experimented with using some 5V line that turns on and off accordingly with Saab's audio components (i.e. turns on when the key is in and the radio is on)? This way, the DC-DC converter could be eliminated, and it would be easier to turn on/off any aftermarket modules (like your project here) accordingly with the radio (even if they ignition was set to off, not just on)

Having steering button control is nice, so I will probably build this project and test it out. And I bet this will sound better than the cheap BT module I have.

On an unrelated note - does your CAN bus circuit only allow for steering button control, or can it also display music data on the SID? If not, is that a possibility?

**Comment by leighleighleigh** [comment]
Hi there!
I have not experimented with using these 5V supplies - although I have probed around the inside of the EHU+AHU, it's very nice that SAAB have labelled everything! I think that with some luck we could tune the equaliser over I2C for better sound quality...

This particulate bluetooth module project is now quite old - I have been working on a newer version that utilises a proper BM83 bluetooth audio module, and I intend to utilise the CAN-bus wake-up feature that should allow it to come online/offline with the rest of the infotainment system. Due to of lack of time + the global semiconductor shortage, I haven't uploaded any progress on this, sorry! 

On the SID idea - I also have a (quite old) project dedicated to SID-hacking, and I was able to get text displayed. However this is not available through any CAN bus interface (as far as I know), and required dedicated hardware in between the EHU and SID. I also have a similar project with information on how to use the ICM-2 display through it's I2C lines, which is probably easier for a Bluetooth music display.

Thanks,
Leigh

**Comment by jokubasver** [comment]
Thank you for responding. Will be interesting to see your efforts with the BM83 module. In the meantime I'll build this project, and I'll try poking around with those 5V lines to see if there's anything that's usable.

I couldn't find any concrete info on where to tap in in to the CAN bus. Do you know on which wire harness I should connect CAN H and L wires to?

**Comment by leighleighleigh** [comment]
Yes - I recommend tapping into the "LS GMLAN1" and "LS GMLAN2" wires coming from the EHU. I believe #1 is CANH and #2 is CANL. Keep in mind - this bus is "single wire CAN", so you may need to check your CAN transceiver supports this. (I had no issues with the MCP2515).

**Comment by jokubasver** [comment]
Got the PCB soldered up and programmed. I updated some code, included the latest MCP2515 and A2DP libraries, so I might do a pull request if everything works after testing. Sound quality is very nice and much better than my old BT audio module.

Now, onto the steering wheel button controls - I can't seem to find LS GMLAN1 and LS GMLAN2 anywhere in the EHU. I do see them marked on the ICM connector, though. Is that what you meant? Or is there a way to tap into LS GMLAN in the EHU? 

While poking around the ICM connector solder pads, trying to see where exactly I should solder GMLAN wires to on the ICM PCB, I measured a DC short across LS GMLAN1 and LS GMLAN2. Now, I am not too familiar with CAN, but I find that a bit weird. Is that normal?

EDIT:
It works! At first buttons didn't do anything, so I tried my own code - still didn't work. So I tried connecting LS GMLAN1 from the ICM to CAN H, and leaving LS GMLAN2, CAN L unconnected, and that made it work. 

For some reason your code didn't make the buttons work, even though I didn't change any CAN bus logic in my own code. Will submit a pull request as soon as I can for you to check out.

Now it's just time to experiment with available 5V lines, make sure these switch on and off how I want them to, and that they don't drain the battery. Then - cable management and final install :)

**Comment by leighleighleigh** [comment]
That's awesome, I'll review your pull request when I have time 😀

I spliced into the connector, yes, it wasn't very easy though (not much
length on the cable to get access to it).

Most CAN busses have a termination resistor between the two lines, usually
120 Ohms, but for LSGMLAN/SWCAN maybe 4.7Kohm - you might be seeing that as
a DC short with your multimeter?

**Comment by jokubasver** [comment]
I installed an AM1SS-0505SJZ isolated 5V-5V DC-DC converter and Bluetooth noise is gone. Seems like 1W converters are enough for 5V EHU use, as the whole PCB with ESP32, UDA1334A, MCP2515 and AM1SS-0505SJZ draws about 165mA at the voltage input (the max of the DC-DC converter is 200mA, so quite close to the limit, but seems to work just fine)

I still hear noise with CAN H connected to LS GMLAN1. Disconnecting CAN H audio is super clean and noise free.

So just to confirm - are you connecting both CAN H -> LS GMLAN1 and CAN L -> LS GMLAN2, or are you just using CAN H? Even though it works for me just with CAN H, I want to make sure I have everything wired up properly :D
